// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPz_GYdK5fVWmQrfHsMp1CLkbK-Ff6BAU',
    appId: '1:287108188348:web:f6cc8d5b713dcd6fa6a8b9',
    messagingSenderId: '287108188348',
    projectId: 'chatapptest-ef1d1',
    authDomain: 'chatapptest-ef1d1.firebaseapp.com',
    storageBucket: 'chatapptest-ef1d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG-1ZrWLewBR0m_0nkb4YPSGQHTOI3L-U',
    appId: '1:287108188348:android:72ed93b38acaafbba6a8b9',
    messagingSenderId: '287108188348',
    projectId: 'chatapptest-ef1d1',
    storageBucket: 'chatapptest-ef1d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_YdkRwwdhMuC9sJGS07b4DCvEclOZtRk',
    appId: '1:287108188348:ios:844d201beb0e64f3a6a8b9',
    messagingSenderId: '287108188348',
    projectId: 'chatapptest-ef1d1',
    storageBucket: 'chatapptest-ef1d1.appspot.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_YdkRwwdhMuC9sJGS07b4DCvEclOZtRk',
    appId: '1:287108188348:ios:844d201beb0e64f3a6a8b9',
    messagingSenderId: '287108188348',
    projectId: 'chatapptest-ef1d1',
    storageBucket: 'chatapptest-ef1d1.appspot.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPz_GYdK5fVWmQrfHsMp1CLkbK-Ff6BAU',
    appId: '1:287108188348:web:c447f387962520f0a6a8b9',
    messagingSenderId: '287108188348',
    projectId: 'chatapptest-ef1d1',
    authDomain: 'chatapptest-ef1d1.firebaseapp.com',
    storageBucket: 'chatapptest-ef1d1.appspot.com',
  );

}